/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: "jit",
  purge: ["./src/**/*.{js,jsx,ts,tsx}", ],
  plugins: [],
  theme: {
    extend:
    {
      fontFamily: {
        "Lalezar": ["Lalezar", "sans-serif"]
      },
      backgroundImage: {
        'generalInfo': "url('./assets/neonbrand-zFSo6bnZJTw-unsplash.png')",
        'js': "url('./assets/480px-Unofficial_JavaScript_logo_2.svg.png')",
        'Csharp': "url('./assets/c--4.png')",
        'bootstrap': "url('./assets/bootstrap-logo-vector.png')",
        'java': "url('./assets/logo-java-text-color.png')",
        'mentoring': "url('./assets/business-people-with-finance-chart.png')",
        'license': "url('./assets/young-handsome-curly-student-man-with-notebooks-isolated-white-wall.png')",
        'construction': "url('./assets/cheerful-mood-group-people-business-conference-modern-classroom-daytime.png')",
        'news': "url('./assets/scott-graham-5fNmWej4tAA-unsplash.png')",
        'suggestions': "url('./assets/thought-catalog-505eectW54k-unsplash.png')",
        'landingHeader': "url('./assets/brooke-cagle-g1Kr4Ozfoac-unsplash.png')",
        'coursesHeader': "url('./assets/Group 87.png')",
        'detailsHeader': "url('./assets/neonbrand-1-aA2Fadydc-unsplash.png')",
        'bamboIcon': "url('./assets/bamboo c).png')",
        'jsMark': "url('./assets/jsMark.png')",
      },
    },
    gridTemplateRows: {
      '20': 'repeat(20, minmax(0, 1fr))',
    },
    gridTemplateColumns: {
      '20': 'repeat(20, minmax(0, 1fr))',
    },
    gridRowStart: {
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
      '13': '13',
      '14': '14',
      '15': '15',
      '16': '16',
      '17': '17',
      '18': '18',
      '19': '19',
      '20': '20',
      '21': '21',
    },
    gridRowEnd: {
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
      '13': '13',
      '14': '14',
      '15': '15',
      '16': '16',
      '17': '17',
      '18': '18',
      '19': '19',
      '20': '20',
      '21': '21',
    },
    gridColumnStart: {
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
      '13': '13',
      '14': '14',
      '15': '15',
      '16': '16',
      '17': '17',
      '18': '18',
      '19': '19',
      '20': '20',
      '21': '21',
    },
    gridColumnEnd: {
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
      '13': '13',
      '14': '14',
      '15': '15',
      '16': '16',
      '17': '17',
      '18': '18',
      '19': '19',
      '20': '20',
      '21': '21',
    }
  },
}
